import { createPrototypeAppSummary } from "../../index";

import type {
  PrototypeActivityEntry,
  PrototypeAppKey,
  PrototypeDashboardSummaryData,
  PrototypeDraftSummary,
  PrototypeProfileSummary,
  PrototypeServiceCatalogueEntry,
  PrototypeSubmissionSummaryMetadata,
  PrototypeSubmissionSummaryDownload,
  PrototypeSubmittedRequestSummary,
  PrototypeUploadedDocument,
  PrototypeUploadPolicy,
  PrototypeValidationError,
  PrototypeWorkflowData
} from "../../index";
import type { FrontendPublicUrlConfig } from "../publicUrls";

export const mockProfileSummary: PrototypeProfileSummary = {
  displayName: "Avery Taylor",
  email: "avery.taylor@example.test",
  identityStrength: "verified"
};

export function createMockServiceCatalogue(publicUrls: FrontendPublicUrlConfig): PrototypeServiceCatalogueEntry[] {
  return [
    {
      appKey: "seniors-card",
      description: "Check eligibility and prepare a Seniors Card application.",
      href: publicUrls["seniors-card"],
      label: "Seniors Card",
      status: "available"
    },
    {
      appKey: "rental-security-subsidy",
      description: "Prepare rental support information and track a subsidy request.",
      href: publicUrls["rental-security-subsidy"],
      label: "Rental Security Subsidy",
      status: "available"
    }
  ];
}

export function createMockValidationErrors(appKey: Exclude<PrototypeAppKey, "dashboard">): PrototypeValidationError[] {
  if (appKey === "rental-security-subsidy") {
    return [
      {
        fieldPath: "rentalProperty.weeklyRent",
        message: "Enter the weekly rent amount for the property."
      }
    ];
  }

  return [
    {
      fieldPath: "eligibility.dateOfBirth",
      message: "Enter a date of birth that confirms eligibility."
    }
  ];
}

export const mockUploadPolicy: PrototypeUploadPolicy = {
  acceptedFileTypes: ["application/pdf", "image/jpeg", "image/png"],
  maxFileSizeBytes: 10 * 1024 * 1024,
  rejectedExample: {
    fieldPath: "supportingDocuments[0].file",
    message: "Upload a PDF, JPG or PNG file under 10 MB."
  }
};

export function createMockUploadedDocuments(appKey: Exclude<PrototypeAppKey, "dashboard">): PrototypeUploadedDocument[] {
  const prefix = appKey === "seniors-card" ? "identity" : "rental-property";

  return [
    {
      category: appKey === "seniors-card" ? "Identity evidence" : "Rental evidence",
      fileName: `${prefix}-evidence.pdf`,
      sizeBytes: 512_000,
      status: "uploaded"
    },
    {
      category: "Rejected example",
      fileName: `${prefix}-archive.zip`,
      message: mockUploadPolicy.rejectedExample.message,
      sizeBytes: 14_000_000,
      status: "rejected"
    }
  ];
}

export function createMockDraftSummary(appKey: Exclude<PrototypeAppKey, "dashboard">): PrototypeDraftSummary {
  return {
    appKey,
    draftId: `${appKey}-draft-001`,
    lastUpdated: "2026-06-12T01:30:00.000Z",
    status: "DRAFT",
    title: createPrototypeAppSummary(appKey).label
  };
}

export function createMockSubmittedRequestSummary(
  appKey: Exclude<PrototypeAppKey, "dashboard">
): PrototypeSubmittedRequestSummary {
  return {
    appKey,
    referenceNumber: appKey === "seniors-card" ? "SC-2026-0001" : "RSS-2026-0001",
    status: appKey === "seniors-card" ? "APPROVED" : "IN_REVIEW",
    submittedAt: "2026-06-12T02:15:00.000Z",
    title: createPrototypeAppSummary(appKey).label
  };
}

export function createMockActivity(appKey: Exclude<PrototypeAppKey, "dashboard">): PrototypeActivityEntry[] {
  const submittedRequest = createMockSubmittedRequestSummary(appKey);

  return [
    {
      at: "2026-06-12T01:30:00.000Z",
      description: "Draft saved",
      status: "DRAFT"
    },
    {
      at: submittedRequest.submittedAt,
      description: `${submittedRequest.referenceNumber} submitted`,
      status: submittedRequest.status
    }
  ];
}

export function createMockSubmissionSummaryMetadata(
  appKey: Exclude<PrototypeAppKey, "dashboard">
): PrototypeSubmissionSummaryMetadata {
  const submittedRequest = createMockSubmittedRequestSummary(appKey);

  return {
    filename: `${submittedRequest.referenceNumber.toLowerCase()}-summary.txt`,
    href: `/service-requests/${submittedRequest.referenceNumber}/summary/download`,
    referenceNumber: submittedRequest.referenceNumber
  };
}

export function createMockSubmissionSummaryDownload(
  appKey: Exclude<PrototypeAppKey, "dashboard">,
  referenceNumber = createMockSubmittedRequestSummary(appKey).referenceNumber
): PrototypeSubmissionSummaryDownload {
  const app = createPrototypeAppSummary(appKey);

  return {
    body: [
      `${app.label} prototype submission summary`,
      `Reference: ${referenceNumber}`,
      "This text file is generated by the frontend mock runtime for review only."
    ].join("\n"),
    contentType: "text/plain",
    filename: `${referenceNumber.toLowerCase()}-summary.txt`,
    referenceNumber
  };
}

export function createMockDashboardSummaryData(publicUrls: FrontendPublicUrlConfig): PrototypeDashboardSummaryData {
  return {
    activity: [...createMockActivity("seniors-card"), ...createMockActivity("rental-security-subsidy")],
    availableServices: createMockServiceCatalogue(publicUrls),
    drafts: [createMockDraftSummary("seniors-card")],
    profile: mockProfileSummary,
    submittedRequests: [
      createMockSubmittedRequestSummary("seniors-card"),
      createMockSubmittedRequestSummary("rental-security-subsidy")
    ]
  };
}

export function createMockWorkflowData(appKey: Exclude<PrototypeAppKey, "dashboard">): PrototypeWorkflowData {
  return {
    activity: createMockActivity(appKey),
    app: createPrototypeAppSummary(appKey),
    draft: createMockDraftSummary(appKey),
    profile: mockProfileSummary,
    submittedRequest: createMockSubmittedRequestSummary(appKey),
    supportingDocuments: createMockUploadedDocuments(appKey),
    uploadPolicy: mockUploadPolicy,
    validationErrors: createMockValidationErrors(appKey)
  };
}
