export const prototypeTokens = {
  source: "qhds-reference-css-snapshot",
  selectedPalette: "qld-health",
  color: {
    primitive: {
      accent: "#84d3ff",
      darkBackground: "#005eb8",
      darkBackgroundAlt: "#001d74",
      darkFocus: "#c6ffff",
      darkModeBackground: "#000053",
      darkVisitedLink: "#ffffff",
      heading: "#000053",
      lightBackground: "#e6f6ff",
      lightBackgroundAlt: "#e3e7ea",
      lightFocus: "#002e85",
      link: "#005eb8",
      text: "#353535",
      textLighter: "#636363",
      white: "#ffffff"
    },
    qldVariables: [
      "--QLD-color-light__heading",
      "--QLD-color-light__text",
      "--QLD-color-light__link",
      "--QLD-color-light__focus",
      "--QLD-color-light__background",
      "--QLD-color-light__background--alt",
      "--QLD-color-dark__background",
      "--QLD-color-dark__background--alt",
      "--QLD-color-dark__focus",
      "--QLD-underline__thickness-thin",
      "--QLD-underline__thickness-thick",
      "--QLD-underline__offset"
    ],
    semanticVariables: [
      "--ssq-color-background",
      "--ssq-color-surface",
      "--ssq-color-surface-alt",
      "--ssq-color-heading",
      "--ssq-color-text",
      "--ssq-color-muted",
      "--ssq-color-border",
      "--ssq-color-border-strong",
      "--ssq-color-action",
      "--ssq-color-action-text",
      "--ssq-color-link",
      "--ssq-color-link-visited",
      "--ssq-color-link-decoration",
      "--ssq-color-error",
      "--ssq-color-error-border",
      "--ssq-color-error-background",
      "--ssq-color-invalid-border",
      "--ssq-color-focus",
      "--ssq-color-header-accent",
      "--ssq-color-header-background",
      "--ssq-color-header-text",
      "--ssq-color-info-background",
      "--ssq-color-info-border",
      "--ssq-color-info-text",
      "--ssq-color-success-background",
      "--ssq-color-success-border",
      "--ssq-color-success-text",
      "--ssq-color-warning-background",
      "--ssq-color-warning-border",
      "--ssq-color-warning-text",
      "--ssq-color-error-text"
    ]
  },
  radius: {
    qhdsSm: "12px",
    sm: "4px",
    md: "0.5rem"
  },
  space: {
    0: "0",
    1: "0.25rem",
    2: "0.5rem",
    3: "0.75rem",
    4: "1rem",
    5: "1.25rem",
    6: "1.5rem",
    7: "2rem",
    8: "2.25rem",
    9: "2.5rem",
    10: "3rem",
    12: "4rem",
    16: "10rem"
  },
  typography: {
    fontFamilyBase: '"Noto Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
    fontFamilyHeading: '"Noto Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
    fontFamilySiteTitle: '"Noto Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
    fontSizeBase: "1rem",
    fontWeightBold: 700,
    fontWeightRegular: 400,
    fontWeightSemibold: 600,
    h1Desktop: "3rem",
    h1DesktopLineHeight: "3.75rem",
    h1Mobile: "2rem",
    h1MobileLineHeight: "2.5rem",
    h2Desktop: "2rem",
    h2DesktopLineHeight: "2.5rem",
    h2Mobile: "1.75rem",
    h2MobileLineHeight: "2.25rem",
    h3: "1.5rem",
    h3LineHeight: "2rem",
    h4: "1.25rem",
    h4LineHeight: "1.5rem",
    h5: "1rem",
    h5LineHeight: "1.25rem",
    h6: "0.875rem",
    h6LineHeight: "1rem",
    leadDesktop: "1.5rem",
    leadMobile: "1.25rem",
    letterSpacingDefault: 0,
    lineHeightBase: 1.5,
    lineHeightParagraph: 1.75
  },
  layout: {
    contentBlockSpacingDesktop: "3rem",
    contentBlockSpacingMobile: "2rem",
    sectionPaddingDesktop: "4rem",
    sectionPaddingMobile: "2.25rem"
  }
} as const;
