import { randomUUID } from "node:crypto";

import type { SupportingDocumentRecord } from "../repositories/prototypeRepository.js";

export const PROTOTYPE_EVIDENCE_UPLOAD_STATUS = "STORED_PROTOTYPE";
export const PROTOTYPE_EVIDENCE_RETENTION_POLICY = "PROTOTYPE_REVIEW_90_DAYS";

export type PrototypeEvidenceScanStatus = "AVAILABLE" | "PENDING_SCAN" | "QUARANTINED" | "REJECTED";

export interface StoredPrototypeEvidence {
  retentionPolicy: string;
  scanStatus: PrototypeEvidenceScanStatus;
  storageKey: string;
  uploadStatus: string;
  metadata: Record<string, unknown>;
}

export interface EvidenceDownload {
  body: string;
  contentType: "text/plain; charset=utf-8";
  fileName: string;
}

export type EvidenceDownloadResult =
  | {
      ok: true;
      download: EvidenceDownload;
    }
  | {
      ok: false;
      code: "DOCUMENT_NOT_AVAILABLE";
      message: string;
    };

export class EvidenceStorageService {
  createStoredPrototypeEvidence(input: {
    category: string;
    correlationId?: string;
    customerId: string;
    fileExtension: string;
    fileName: string;
    mimeType: string;
    personKey: string;
    sizeBytes: number;
    transactionKey?: string;
  }): StoredPrototypeEvidence {
    const scanStatus = determinePrototypeScanStatus(input.fileName);

    return {
      metadata: {
        category: input.category,
        correlationId: input.correlationId,
        localStorageMode: "prototype-evidence-storage-adapter",
        personKey: input.personKey,
        productionNext: {
          malwareScanning: "replace deterministic prototype scan",
          privateObjectStorage: "replace metadata-backed local adapter",
          retentionSchedule: "replace prototype review retention class"
        },
        retention: {
          policy: PROTOTYPE_EVIDENCE_RETENTION_POLICY,
          reviewDisposition: "delete-after-local-review"
        },
        scan: {
          engine: "prototype-deterministic-scan",
          status: scanStatus
        },
        transactionKey: input.transactionKey ?? "unknown"
      },
      retentionPolicy: PROTOTYPE_EVIDENCE_RETENTION_POLICY,
      scanStatus,
      storageKey: `prototype-evidence/${input.customerId}/${randomUUID()}${input.fileExtension}`,
      uploadStatus: PROTOTYPE_EVIDENCE_UPLOAD_STATUS
    };
  }

  createDownload(document: SupportingDocumentRecord): EvidenceDownloadResult {
    if (!isDocumentAvailable(document)) {
      return {
        ok: false,
        code: "DOCUMENT_NOT_AVAILABLE",
        message: "Supporting document is not available for download."
      };
    }

    return {
      ok: true,
      download: {
        body: [
          "SSQ prototype supporting document artefact",
          `Document ID: ${document.id}`,
          `Original filename: ${document.fileName}`,
          `Category: ${document.category}`,
          `MIME type: ${document.mimeType}`,
          `Size bytes: ${document.sizeBytes}`,
          `Storage key: ${document.storageKey}`,
          `Upload status: ${document.uploadStatus}`,
          `Scan status: ${document.scanStatus}`,
          `Retention policy: ${document.retentionPolicy}`,
          "",
          "This text file is generated by the local prototype evidence storage adapter.",
          "It proves the private download boundary without claiming production binary storage."
        ].join("\n"),
        contentType: "text/plain; charset=utf-8",
        fileName: `${sanitizeFileName(document.fileName)}.prototype.txt`
      }
    };
  }
}

export function isDocumentAvailable(document: SupportingDocumentRecord): boolean {
  return document.uploadStatus !== "REJECTED" && (document.scanStatus === "AVAILABLE" || document.scanStatus === "PASSED");
}

function determinePrototypeScanStatus(fileName: string): PrototypeEvidenceScanStatus {
  const normalizedFileName = fileName.toLowerCase();

  if (normalizedFileName.includes("quarantine")) {
    return "QUARANTINED";
  }

  if (normalizedFileName.includes("malware") || normalizedFileName.includes("reject")) {
    return "REJECTED";
  }

  if (normalizedFileName.includes("pending")) {
    return "PENDING_SCAN";
  }

  return "AVAILABLE";
}

function sanitizeFileName(fileName: string): string {
  return fileName.replace(/[^a-zA-Z0-9._-]/g, "_");
}
